[package]
name = "sipal"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "1.3.2"

[dependencies.minifb]
version = "0.23.0"
optional = true
[features]
default = ["minifb_window", "std"]
std = []
minifb_window = ["dep:minifb"]
[dev-dependencies]
glm = "0.2.3"